$(function(){
    feather.replace()
    $('.popular_slider').slick({
        slidesToShow:3,
        centerMode:true,
        centerPadding:"200px",
        arrows:false,
        focusOnSelect:true,
      });
})